[package]
name = "test2"
version = "0.1.0"
authors = ["test@example.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test2"
path = "src/main.rs"

[features]
coverage = []

[dependencies]
#argh = "*"
clap = "*"
clap_allgen = "*"
color-eyre = "*"
dialoguer = "*"
dirs = "*"
#figment = { version = "*", features = ["json", "toml", "yaml", "env"] }
config-rs = "*"
log = "*"
insta = "*"
pretty_env_logger = "*"
requestty = "*"
snafu = "*"
template-eyre = "*"
tracing = "*"
tracing-tree = "*"
trycmd = "*"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
backtrace.opt-level = 3
